create table
  public.products (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name character varying not null,
    price real not null,
    inventory smallint not null,
    description text not null,
    "imageUrl" text null,
    category character varying not null,
    constraint products_pkey primary key (id)
  ) tablespace pg_default;


  create table
  public.customers (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name character varying not null,
    email character varying not null,
    address text not null,
    zipcode character varying not null,
    constraint Customer_pkey primary key (id),
    constraint Customer_email_key unique (email)
  ) tablespace pg_default;


  create table
  public.sales (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    quantity smallint not null,
    total_price real not null,
    customer bigint not null,
    product bigint not null,
    constraint sales_pkey primary key (id),
    constraint sales_customer_fkey foreign key (customer) references customers (id),
    constraint sales_product_fkey foreign key (product) references products (id)
  ) tablespace pg_default;


  create table
  public.stores (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name character varying not null,
    address text not null,
    timings character varying not null,
    description text not null,
    constraint stores_pkey primary key (id)
  ) tablespace pg_default;