create table
  public.products (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name character varying not null,
    price real not null,
    inventory smallint not null,
    description text not null,
    imageUrl text null,
    category character varying not null,
    constraint products_pkey primary key (id, created_at)
  ) tablespace pg_default;